name: mustache
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates
  - libffi=3.4.2
  - libzlib=1.2.12
  - ncurses=6.3
  - openssl=3.0.3
  - pip=22.1.2
  - python=3.9.13
  - python_abi=3.9
  - readline=8.1.2
  - setuptools=62.3.4
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - asciitree==0.3.3
    - certifi==2022.5.18.1
    - charset-normalizer==2.0.12
    - click==8.1.3
    - cooler==0.8.11
    - cytoolz==0.10.1
    - dill==0.3.5.1
    - h5py==3.7.0
    - hic-straw==1.3.1
    - idna==3.3
    - multiprocess==0.70.13
    - mustache-hic==1.2.7
    - numpy==1.22.4
    - packaging==21.3
    - pandas==1.4.2
    - pathlib==1.0.1
    - patsy==0.5.2
    - pybind11==2.9.2
    - pyfaidx==0.7.0
    - pypairix==0.3.7
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - requests==2.28.0
    - scipy==1.8.1
    - simplejson==3.17.6
    - six==1.16.0
    - statsmodels==0.13.2
    - toolz==0.11.2
    - urllib3==1.26.9
